### ISSUE TITLE
Please implement baasil logs -f

### ISSUE THREAD

**Issue by heiba** [SocketCluster/baasil-cli#1]
Hello @jondubois 

Superb work on the baasil client.

We can currently apply this command: baasil logs 
which wraps docker logs <container-Id>

Please implement baasil logs -f
which will apply docker logs <container-Id> -f

This way the logs are in a stream and we can follow it in a seamless manner.

Reference: https://docs.docker.com/engine/reference/commandline/logs/

**Comment by jondubois** [comment]
This has been fixed. `baasil@v1.3.8`.
